/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EventList: typeof import('./src/components/EventList.vue')['default']
    LoginView: typeof import('./src/components/LoginView.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NInput: typeof import('naive-ui')['NInput']
    NInputGroup: typeof import('naive-ui')['NInputGroup']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NPagination: typeof import('naive-ui')['NPagination']
    NPopconfirm: typeof import('naive-ui')['NPopconfirm']
    NPopover: typeof import('naive-ui')['NPopover']
    NSelect: typeof import('naive-ui')['NSelect']
    NTag: typeof import('naive-ui')['NTag']
    NTooltip: typeof import('naive-ui')['NTooltip']
    SessionDetail: typeof import('./src/components/SessionDetail.vue')['default']
    SessionList: typeof import('./src/components/SessionList.vue')['default']
    SettingsPanel: typeof import('./src/components/SettingsPanel.vue')['default']
    SplitDivider: typeof import('./src/components/SplitDivider.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UsageDonutChart: typeof import('./src/components/UsageDonutChart.vue')['default']
    UsagePanel: typeof import('./src/components/UsagePanel.vue')['default']
    UsageTrendChart: typeof import('./src/components/UsageTrendChart.vue')['default']
  }
}
